# Docker compose file allowing to launch a Firefox container resistant to WebRTC IP leak. It runs under X
# (Xorg/XWayland).
#
# Copyright (C) 2024 Guillaume Nibert <guillaume.nibert@snowpack.eu>,
#                    Sébastien Tixeuil <sebastien.tixeuil@lip6.fr>,
#                    Baptiste Polvé <baptiste.polve@snowpack.eu>,
#                    Nana J. Bakalafoua M'boussi <nana.bakalafoua@snowpack.eu>,
#                    Xuan Son Nguyen <xuanson.nguyen@snowpack.eu>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Maintainer: Guillaume Nibert <guillaume.nibert@snowpack.eu>
services:
    firefox-docker-x-linux-automated-benchmarks:
        # To up container as a non-root user that have the same UID:GID of the non-root host user.
        user: "$UID:$GID"
        networks:
            firefox-br-x:
                ipv4_address: 172.16.240.10
                ipv6_address: fde4:7c37:e8f9::2
        # AppArmor profile
        #
        # Necessary to perform screen sharing and share other variables, such as desktop mode (light/dark)... It would 
        # be relevant to create an apparmor profile dedicated to this container, inspired by the one for docker-default, 
        # firefox-snap and/or firefox-normal.
        # Some ideas : https://apparmor.pujol.io/
        security_opt:
            - apparmor:unconfined  # TODO: create a dedicated profile
        volumes:
            - $XDG_RUNTIME_DIR/pulse/native:$XDG_RUNTIME_DIR/pulse/native  # Accessing Pulseaudio's Unix host socket.
            - /tmp/.X11-unix:/tmp/.X11-unix # Access to X11/XWayland's Unix host socket.
            - /usr/share/icons:/usr/share/icons:ro  # Allows the container to have the same icons as the host.
            - $XDG_RUNTIME_DIR/dconf:$XDG_RUNTIME_DIR/dconf  # GNOME configurations for Firefox settings.
            - $XDG_RUNTIME_DIR/bus:$XDG_RUNTIME_DIR/bus  # Allows the container to send/receive messages from DBus.
            - /home/$USER/Downloads:/home/$USER/Downloads/  # Allows Firefox to download to the host's Downloads folder.
            - /home/$USER/Firefox_Docker_Profiles:/home/$USER/.mozilla/firefox/  # Keep Firefox settings/bookmarks...
            - /dev/video0:/dev/video0  # Allows the container to have access to the camera.
            - /dev/dri/card0:/dev/dri/card0  # Allows the container to have access to host's GPU core fonctionalities.
            - /dev/dri/renderD128:/dev/dri/renderD128  # Allows the container to have access to host's GPU 3D rendering.
            
        # Environement variables
        #
        # For XDG_* environnement variables, see : https://www.freedesktop.org/software/systemd/man/pam_systemd.html
        # and https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.
        #
        # For the X.org DISPLAY variable, see :
        # https://www.x.org/archive/X11R6.8.0/doc/X.7.html
        #
        # For the PULSE_SERVER variable, see :
        # https://www.freedesktop.org/wiki/Software/PulseAudio/FAQ/index.html#index5h2
        environment:
            - XDG_SESSION_CLASS=user  
            - XDG_CURRENT_DESKTOP=ubuntu:GNOME
            - XDG_MENU_PREFIX=gnome-
            - XDG_SESSION_DESKTOP=ubuntu
            - XDG_RUNTIME_DIR=/run/user/$UID
            - XDG_SESSION_TYPE=x11
            - DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
            - DISPLAY=:0
            - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native

        # /dev/dri/*: Sharing GPU host's GPU functionalities with the container.
        #
        # /dev/video* Camera/Webcam
        #
        # To check which /dev/video* is the webcam, run : v4l2-ctl --list-devices and change /dev/video0 to the
        # appropriate one.
        # More info about /dev/video* devices at : https://tldp.org/HOWTO/Webcam-HOWTO/dev-intro.html
        devices:
            - /dev/dri/card0:/dev/dri/card0
            - /dev/dri/renderD128:/dev/dri/renderD128
            - /dev/video0:/dev/video0
        build:
            dockerfile: Dockerfile-firefox-x-linux-automated-benchmarks
            # Mandatory and optional args
            #
            # UID, GID, USERNAME (mandatory)
            # The user of the container should match that of the host, in particular, its UID, GID because the sockets
            # (pulse...) go through run/user/UID, this also facilitates the management of permissions (using
            # chown with UID:GID). For simplicity, it is also interesting that the host and container usernames are
            # the same (cf. sharing of the Downloads folder and the firefox profile).
            #
            # RENDER_GID: render group id needed to share GPU functionalities with the container.
            #
            # FF_LANG (optional)
            # The FF_LANG (Firefox language) argument can be modified according to the list of language codes here:
            # https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/README.txt
            # By default, this container use the latest version of Firefox, this can be modified in the dockerfile.
            #
            # LINUX_ARCH (mandatory) [linux-i686 | linux-x86_64]: check with : `uname -m`
            # 
            # UBUNTU_MIRROR_ARCHIVE_HTTP (optional) [fr-archive-http]: https://launchpad.net/ubuntu/+archivemirrors
            # UBUNTU_MIRROR_ARCHIVE_HTTPS (optional) [fr-archive-https]: https://launchpad.net/ubuntu/+archivemirrors
            # Value: name of the file located in the ubuntu-archive-mirrors folder (without the .list file extension)
            args:
                UID: $UID
                GID: $GID
                RENDER_GID: $RENDER_GID
                USERNAME: $USER
                FF_LANG: en-GB
                LINUX_ARCH: linux-x86_64
                UBUNTU_MIRROR_ARCHIVE_HTTP: fr-archive-http
                UBUNTU_MIRROR_ARCHIVE_HTTPS: fr-archive-https

# IPv4 private space/IPv6 ULA
networks:
    firefox-br-x:
        enable_ipv6: true
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.240.0/24
                  gateway: 172.16.240.1
                - subnet: fde4:7c37:e8f9::/64
                  gateway: fde4:7c37:e8f9::1
